name: score_tracker_app
description: A score tracking application for students and groups.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ensure your SDK constraint is compatible

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.1
  uuid: ^4.1.0
  fl_chart: ^0.63.0
  path_provider: ^2.0.11 # Or the latest stable version
  share_plus: ^7.0.0    # Or the latest stable version
  image_picker: ^1.0.4 # Or the latest stable version
  firebase_storage: ^11.5.6 # Or the latest stable version
  collection: ^1.18.0 # Ensure this is also present for firstWhereOrNull

  # Firebase dependencies - using latest stable versions for compatibility
  firebase_core: ^2.27.0 # Updated to latest stable
  cloud_firestore: ^4.17.5 # Updated to latest stable
  firebase_auth: ^4.17.5 # Updated to latest stable

  json_annotation: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6 # Keep this for json_serializable

flutter:
  uses-material-design: true # <-- THIS IS THE CORRECT PLACEMENT AND INDENTATION!
 # //assets:
#   - assets/icons/indian_flag.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can be optionally sized and aligned.
  #
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
