// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP8qZ4cSAoGwSli7w7Dhu5VYYZDvIPmbw',
    appId: '1:405298057035:web:7ac87bcb391d65b60762ce',
    messagingSenderId: '405298057035',
    projectId: 'scoretrackerapp-16051',
    authDomain: 'scoretrackerapp-16051.firebaseapp.com',
    storageBucket: 'scoretrackerapp-16051.firebasestorage.app',
    measurementId: 'G-K6L8DDM6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB1FEoeMga34PFw89gj24IXNKGRa8isQg',
    appId: '1:405298057035:android:a90662ccb95d0a000762ce',
    messagingSenderId: '405298057035',
    projectId: 'scoretrackerapp-16051',
    storageBucket: 'scoretrackerapp-16051.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKCKNkAuGPosPqVPGQbUEbRspnnnXr-Eo',
    appId: '1:405298057035:ios:435681ce23dcce000762ce',
    messagingSenderId: '405298057035',
    projectId: 'scoretrackerapp-16051',
    storageBucket: 'scoretrackerapp-16051.firebasestorage.app',
    iosBundleId: 'com.example.scoreTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKCKNkAuGPosPqVPGQbUEbRspnnnXr-Eo',
    appId: '1:405298057035:ios:435681ce23dcce000762ce',
    messagingSenderId: '405298057035',
    projectId: 'scoretrackerapp-16051',
    storageBucket: 'scoretrackerapp-16051.firebasestorage.app',
    iosBundleId: 'com.example.scoreTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP8qZ4cSAoGwSli7w7Dhu5VYYZDvIPmbw',
    appId: '1:405298057035:web:4354681eeace06200762ce',
    messagingSenderId: '405298057035',
    projectId: 'scoretrackerapp-16051',
    authDomain: 'scoretrackerapp-16051.firebaseapp.com',
    storageBucket: 'scoretrackerapp-16051.firebasestorage.app',
    measurementId: 'G-4RXQTMGQY6',
  );
}
